### ISSUE TITLE
推理时报错：ModuleNotFoundError: No module named 'legged_robot_personal'

### ISSUE THREAD

**Issue by ziyangfu** [thkkk/FCNet#2]
Hi
    你好，在运行推理时报错。
1. 运行指令如下，训练的模型为DT，2024-06-27_13-36-14
```bash
(fcnet) acs@acs-Legion:~/Downloads/FCNet-main/FCNet/DT/data/data_collect$ bash -c 'python play.py -m hydra/launcher=joblib \
    task=unitree_general \
    aligo_auto_complete_chks=False \
    dt_policy_name=2024-06-27_13-36-14 kv_cache=True \
    headless=True \
    record=False \
    max_episode_length=1500 \
    play_ep_cnt=3 \
    calc_dt_mlp_loss=False \
    num_envs=2048 \
    simplify_print_info=False \
    multi_gpu=True \
    dummy=False \
    resume=True \
    add_noise=True \
    push_robots=True > play.log 2>&1'
```
2. 报错信息如下：
```bash
availble_gpus: [0]
[2024-06-27 15:50:15,346][HYDRA] Joblib.Parallel(n_jobs=-1,backend=loky,prefer=processes,require=None,verbose=0,timeout=None,pre_dispatch=2*n_jobs,batch_size=auto,temp_folder=None,max_nbytes=None,mmap_mode=r) is launching 1 jobs
[2024-06-27 15:50:15,346][HYDRA] Launching jobs, sweep output dir : multirun/2024-06-27/15-50-15
[2024-06-27 15:50:15,347][HYDRA] 	#0 : task=unitree_general aligo_auto_complete_chks=False dt_policy_name=2024-06-27_13-36-14 kv_cache=True headless=True record=False max_episode_length=1500 play_ep_cnt=3 calc_dt_mlp_loss=False num_envs=2048 simplify_print_info=False multi_gpu=True dummy=False resume=True add_noise=True push_robots=True
Error executing job with overrides: ['task=unitree_general', 'aligo_auto_complete_chks=False', 'dt_policy_name=2024-06-27_13-36-14', 'kv_cache=True', 'headless=True', 'record=False', 'max_episode_length=1500', 'play_ep_cnt=3', 'calc_dt_mlp_loss=False', 'num_envs=2048', 'simplify_print_info=False', 'multi_gpu=True', 'dummy=False', 'resume=True', 'add_noise=True', 'push_robots=True']
Traceback (most recent call last):
  File "play.py", line 296, in <module>
    main()
  File "/home/acs/.conda/envs/fcnet/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/acs/.conda/envs/fcnet/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/acs/.conda/envs/fcnet/lib/python3.8/site-packages/hydra/_internal/utils.py", line 465, in _run_app
    run_and_report(
  File "/home/acs/.conda/envs/fcnet/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/acs/.conda/envs/fcnet/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/acs/.conda/envs/fcnet/lib/python3.8/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "/home/acs/.conda/envs/fcnet/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/home/acs/.conda/envs/fcnet/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 181, in sweep
    _ = r.return_value
  File "/home/acs/.conda/envs/fcnet/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
ModuleNotFoundError: No module named 'legged_robot_personal'
print_inference_action_time False
{'task_name': 'unitree_general', 'headless': True, 'seq_len': None, 'local_rank': 0, 'resume': True, 'num_envs': 2048, 'load_run': None, 'checkpoint': None, 'simplify_print_info': False, 'record': False, 'print_inference_action_time': False, 'play_ep_cnt': 3, 'ac_ratio': 1.0, 'max_episode_length': 1500, 'aligo_auto_complete_chks': False, 'crf': 23, 'dt_policy_name': '2024-06-27_13-36-14', 'dummy': False, 'add_noise': True, 'push_robots': True, 'personal': True, 'multi_gpu': True, 'kv_cache': True, 'legged_gym_version_checked': 'new', 'model_name': None, 'model_name_checked': None, 'dt_mode_name': 'as_a', 'limit_mode_name': None, 'reward_limit': '', 'data_save_to': '../data', 'remerge_sub_data': False, 'total_collect_samples': '', 'max_workers': None, 'test_train_mode': False, 'save_data': None, 'calc_dt_mlp_loss': False, 'skip_episodes': 0, 'max_used_memory': 1000, 'task_config_name': None, 'train_log_dir': './log', 'double_v_dim': True, 'time_tag': None, 'd_m': 768, 'n_layer': 12, 'n_head': 12, 'ffn_coef': None, 'epochs': None, 'lr': 0.0001, 'weight_decay': 0.0001, 'optimizer_use_triton': True, 'warmup_ratio': 0.2, 'clip': 1.0, 'dropout': 0.1, 'train_ratio': 0.9, 'batch_size': 240, 'fno_hidden_size': 128, 'width': 128, 'final_hidden_size': 128, 'inv_dyn_model_hidden_size': 128, 'n_modes': 10, 'ctx_dim': 16, 'is_chunk_wise': False, 'data_read_from': './data/data', 'tasks': None, 'test_interval': 1, 'log_root': './log', 'save_interval': None, 'aligo_enable': False, 'use_fp16': False, 'use_flash_attn': False, 'is_causal': False, 'export_model_as_jit': False, 'train': False, 'data_mode': None, 'data_mode_checked': None, 'load_data_mode': None, 'add_last_action': False, 'save_test_best': False, 'use_tensorboard': False, 'use_wandb': False, 'distributed': True, 'data_scale': False, 'max_sample_number': None, 'load_data_statistics': False, 'episode_first_no_backward': False, 'src_dim': None, 'aligo_name': 'mk', 'aligo_data_root_dir': '/postgraduate/data/RL', 'host_name_mapping': {'snfln1648890518-0': 'g39', 'iuxec1648904174-0': 'g42', 'aamhq1648926718-0': 'g41'}, 'task': {'log_dir_name': 'general_unitree', 'total_collect_samples': 1000000, 'max_episode_length': 1500, 'state_dim': 58, 'action_dim': 12, 'reward_limit': 20, 'legged_gym_version': 'new'}, 'dt_mode': {}}

```
3. 查看代码发现
```Python 
legged_gym_root_dir = None
if legged_gym_version == 'old':
    from legged_gym import LEGGED_GYM_ROOT_DIR
legged_gym_root_dir = LEGGED_GYM_ROOT_DIR
elif legged_gym_version == 'new':    # 配置文件中是 new
from legged_robot_personal import LEGGED_ROBOT_PERSONAL_ROOT_DIR   # 代码里没有这个模块
legged_gym_root_dir = LEGGED_ROBOT_PERSONAL_ROOT_DIR

if resume:
    load_run, checkpoint = smart_load_run(join(legged_gym_root_dir, 'logs', log_dir_name), load_run, checkpoint)
``` 
请问是什么原因呢？谢谢

**Comment by thkkk** [comment]
谢谢关注！legged_robot_personal 是online RL模块，我们暂时还没有release这块代码，所以只能根据开发者自己的环境，修改推理代码

**Comment by ziyangfu** [comment]
> 谢谢关注！legged_robot_personal 是online RL模块，我们暂时还没有release这块代码，所以只能根据开发者自己的环境，修改推理代码

好的，谢谢解答，在根据自己的环境修改推理代码方面，能否给一些指导呢？例如参考什么代码，进行哪些修改？
